### ISSUE TITLE
make: *** [veikk-linux-driver-gui] Error 1

### ISSUE THREAD

**Issue by Ekitai** [jlam55555/veikk-linux-driver-gui#17] opened 2021-03-05 03:24 UTC
I can't make file, it shows this error:
`collect2: error: ld returned 1 exit status
Makefile:164: recipe for target 'veikk-linux-driver-gui' failed
make: *** [veikk-linux-driver-gui] Error 1
`

**Comment by jlam55555** [comment] 2021-06-26 16:55
Can you show the full context for this? (Show all compilation steps, make/Qt versions). Can't reproduce this error without additional context.

Closing for now, reopen if you have more details.

**Closed as completed by jlam55555** 2021-06-26 16:55 UTC
